# default_config:
homeassistant:

# DB config
recorder:
  purge_keep_days: 365
  db_url: !secret db_connection

# Metric store config
influxdb:
  api_version: 2
  host: influxdb.home
  port: 8086
  ssl: false
  verify_ssl: false
  organization: !secret influxdb_org
  bucket: !secret influxdb_bucket
  token: !secret influxdb_token

# Allow reverse proxy
http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

backup:
config:
history:
logbook:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  # extra_module_url:
  #   # Add floorplan
  #   - /local/floorplan.js
  #   # Add bubble-card
  #   - /local/bubble-card.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
