# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
db_connection: !env_var DB_CONNECTION
influxdb_org: !env_var INFLUXDB_ORG
influxdb_bucket: !env_var INFLUXDB_BUCKET
influxdb_token: !env_var INFLUXDB_TOKEN
